### PR TITLE
create a contrib-subdirectory and add some utility scripts

### PR DESCRIPTION
**Pull request by bablokb**
Hi,

this commit creates a directory named "contrib" for user-contributed software. I added my sp3-reader script and my sp3-analyze script to it.

### CODE REVIEW

**Comment by tomek-szczesny** [comment]
That's a great idea.

I think the script headers should be standardized, thus `README.md` should contain a template.
And speaking of that, I think a usage example and output would be much appreciated by someone looking for a script.

**Comment by bablokb** [comment]
The scripts have been discussed in the forum: https://forum.odroid.com/viewtopic.php?f=86&t=43883

I could add a link to that topic from within the scripts.

**Comment by tomek-szczesny** [comment]
Been there, discussed that with you. ;)
Anyway, I'm thinking about a future way to easily browse through that collection of scripts, so someone could pick one they like without testing all of them.

Perhaps `README.md` should contain a summary of scripts instead? I don't know.
And certainly I'm not the one who makes decisions around here. :)

**Comment by leeseungcheol** [comment]
@bablokb  Thank you for your contribution.

This is very useful to analyze power consumption.
But could you update your scripts for the new logging protocol?

https://wiki.odroid.com/accessory/power_supply_battery/smartpower3#logging_protocol

This scripts is only compatible with the old protocol. https://wiki.odroid.com/accessory/power_supply_battery/smartpower3/old_protocol

**Comment by bablokb** [comment]
No, I am using this script with the current logging protocol, with firmware Dec 14, 2021

**Comment by leeseungcheol** [comment]
@bablokb,

Could you update your firmware to v1.8?
[https://github.com/hardkernel/smartpower3/releases/tag/v1.8]()

There are two changes to UDP packets.

1. remove '\0' and carriage return in UDP packet buffers
695b0be10e2d0f9d5f661572a9b7a5e56800215c

2. fix the wrong byte order to CRLF from LFCR
81eb56275a6f8b2fd97281a3e1ece1302d101cb6

**Comment by bablokb** [comment]
Hi,

v1.8 has a problem: https://github.com/hardkernel/smartpower3/commit/81eb56275a6f8b2fd97281a3e1ece1302d101cb6 swaps LFCR -> CRLF (which is correct), but https://github.com/hardkernel/smartpower3/commit/695b0be10e2d0f9d5f661572a9b7a5e56800215c removes not only the `\0`, but also the LF (which is the last char after the swap!) thus leaving the UDP-data with a mere CR as a line-terminator (and UDP-data is not anymore identical to data from serial). See also my comment in https://forum.odroid.com/viewtopic.php?p=341117&sid=113d435937e4efe5d93581ad3607c60e#p341117

Maybe that is the reason why data from v1.8 cannot be analyzed with my script. My reader-script removes the CR, and with neither the LF nor the CR we now have a single endless long data-line from udp. 

I will try to get platformio working this weekend and then provide a pull request fixing https://github.com/hardkernel/smartpower3/commit/695b0be10e2d0f9d5f661572a9b7a5e56800215c (it is actually a one-line fix).

**Comment by leeseungcheol** [comment]
I see.

You mean the line 981 have a problem that removes not only the \0, but also the LF.
https://github.com/hardkernel/smartpower3/commit/695b0be10e2d0f9d5f661572a9b7a5e56800215c#diff-d0d4fda54bb40203c39342dda3a0b3c53b5ca06ceb23387defee5e8d90ac6843R981
And only LF should remain as a line-terminator, not CR in that buffer.

Did I understand correctly?

**Comment by bablokb** [comment]
Almost. 

The current checksum-buffer looks like this (two checksum columns+CRLF+\0):

    df,e3CRLF\0

So removing the CR is difficult and not worth the effort. Don't try to remove the CR, just keep it. It is of no use on Linux, but  you also have Windows-users.

 So 981 should read

    udp.write((uint8_t *)buf3, SIZE_CHECKSUM_BUFFER-1);

Then the following data gets sent:

    df,e3CRLF

which is then identical to the output on the serial line.

**Comment by leeseungcheol** [comment]
Thank you for your explanation.

I've already tested your script with the "udp.write((uint8_t *)buf3, SIZE_CHECKSUM_BUFFER-1)".
It works well. I will merge this PR when you add this change.

**Comment by bablokb** [comment]
I just created a pull-request https://github.com/hardkernel/smartpower3/pull/12 fixing the udp.write

**Pull request merged**
